In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [23]:
df = pd.read_csv("insurance.csv")
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [24]:
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [4]:
df.shape

(1338, 7)

In [6]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [7]:
df.describe()

               age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   expenses  1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 94.5 KB

In [11]:
df = df.dropna()

In [13]:
le = LabelEncoder()
df["sex"] = le.fit_transform(df["sex"])
df["smoker"] = le.fit_transform(df["smoker"])
df["region"] = le.fit_transform(df["region"])
df.head()

   age  sex   bmi  children  smoker  region  expenses
0   19    0  27.9         0       1       3  16884.92
1   18    1  33.8         1       0       2   1725.55
2   28    1  33.0         3       0       2   4449.46
3   33    1  22.7         0       0       1  21984.47
4   32    1  28.9         0       0       1   3866.86

In [15]:
X = df.drop("expenses", axis=1)
y = df["expenses"]

In [25]:
X_train , X_test , Y_train , Y_test = train_test_split(
    X , y , 
    test_size=0.20 , 
    random_state=42
    )
X_train

      age  sex   bmi  children  smoker  region
560    46    0  20.0         2       0       1
1285   47    0  24.3         0       0       0
1142   52    0  24.9         0       0       2
969    39    0  34.3         5       0       2
486    54    0  21.5         3       0       1
...   ...  ...   ...       ...     ...     ...
1095   18    0  31.4         4       0       0
1130   39    0  23.9         5       0       2
1294   58    1  25.2         0       0       0
860    37    0  47.6         2       1       3
1126   55    1  29.9         0       0       3

[1070 rows x 6 columns]

In [26]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[ 0.47222651, -1.0246016 , -1.74857248,  0.73433626, -0.50874702,
        -0.45611589],
       [ 0.54331294, -1.0246016 , -1.03670397, -0.91119211, -0.50874702,
        -1.35325561],
       [ 0.8987451 , -1.0246016 , -0.93737348, -0.91119211, -0.50874702,
         0.44102382],
       ...,
       [ 1.3252637 ,  0.97598911, -0.88770823, -0.91119211, -0.50874702,
        -1.35325561],
       [-0.16755139, -1.0246016 ,  2.82063006,  0.73433626,  1.96561348,
         1.33816354],
       [ 1.1120044 ,  0.97598911, -0.1096194 , -0.91119211, -0.50874702,
         1.33816354]], shape=(1070, 6))

In [18]:
model = LinearRegression()
model.fit(X_train , Y_train)

LinearRegression()

In [27]:
pred = model.predict(X_test)
pred

array([ 8931.64285422,  7108.65837503, 36911.24588592,  9492.1867315 ,
       27005.51458817, 10792.51319722,   219.4619664 , 16940.94699877,
        1057.14434333, 11271.11976436, 28047.33508408,  9427.63503125,
        5329.25523971, 38478.07916194, 40296.31673179, 37133.86645401,
       15296.29024458, 35954.44751436,  9194.99722747, 31513.44163793,
        3798.1729981 , 10071.14543504,  2312.23330804,  7073.55061039,
       11345.29924351, 12913.60653244, 14448.42340264,  6206.0789747 ,
        9916.03458141,  2225.63567221,  9061.06174806, 13111.1535072 ,
        4627.96439893,  3483.42431425,  4402.58881377, 12966.72664374,
        1926.72036749,  8757.35074335, 33311.61922648, 32638.00629978,
        3853.56310911,  4387.19570727, 14080.89095373, 11490.10719794,
        8846.99095184, 12045.0041818 ,  5313.39203076,  3100.3272096 ,
       35556.95223675,  9206.35674505, 15893.88802705,  2415.94128125,
       12391.98367335,  1424.32310327, 13437.63031252, 12516.11125483,
        4307.21904549, 32206.21213403, 13262.4680474 , 12858.13186298,
       14110.93834089, 10546.93834367, 16299.08579591,  7822.11760991,
       11794.83905322,  4100.46371155, 26596.17477561, 10998.35160698,
        2187.15492665,  6140.3965595 , 10685.88540992, 11573.85075044,
       11030.49542391,  9213.43290664, 12021.60962371,  6803.8419613 ,
        7197.66327695, 10804.88499108,  6639.87400964,  8711.40829221,
        3814.71828357, 36582.49908089,  6321.79870769, 30787.03043837,
       34884.81534815, 35211.33034911,  7090.39383797, 12914.31148256,
        9994.01037399, 14410.74910578, 17634.91191538, 35329.85982781,
       32969.52897478,  6120.65639144, 32068.45503527,  9422.69308795,
       29493.43501507,  3732.64127922, 28373.32727915,  5790.16293282,
        5454.38875685,  1827.02904757, 11564.09819224, 15013.8943083 ,
       11670.71538454,  4364.38968582,  9961.1213861 , 31778.26104717,
        -120.99804518, 32894.30779216,  3219.2696343 , 10216.81106111,
       14266.44108362, 31576.47951154, 11415.59339775,  3868.17716893,
       13059.7800495 , 31754.73516068,  8214.15205113,  3300.4764844 ,
        8399.86738514, 10637.0167996 , 15165.31075418,  5716.31386192,
        3820.45418846, 10286.18829118, 10943.42768563, 11060.94920797,
       14496.20151885,  7474.91184498,  5439.7493911 ,  9282.62165185,
        9413.36629458, 12481.52238328,  8277.95858042, 15270.02223074,
        8336.94592501, 31736.66565757, 35835.34643464, 31552.59791089,
        6067.24629673, 12545.61889599,  6062.42076691, 14591.74283636,
        2546.77048244, 32908.72681803,  6329.91657276,  4978.67649387,
       14390.63439584,  6883.90318153, 38719.60793948,  3128.87568504,
        5920.96885328, 31614.79505298, 11609.15557423,  8426.01453248,
       14749.64447488,  9888.75671912, 27156.12417825, 33402.34992909,
       14490.34063067,  1719.93115782, 13117.37402235,  2172.01158273,
        5389.43659769, 11630.65076169, 39739.907942  , 36556.51713768,
       33960.18798704,  3839.57396485,  7410.50185965,  8602.63994151,
       12398.72106088,  4852.87379444,  1993.45305597, 32173.22164758,
       25052.12424031, 17543.1669113 , 26479.89835651, 10222.07483836,
       37194.1815682 ,  -484.63025427,  6849.0684602 ,  7720.57571001,
        4318.75213301,  5132.79875907,  5852.99538148,  4251.32306421,
       15230.19286267, 11167.42670606,  6867.56987012,  2484.43999126,
        1496.95690076, 31876.58882966, 16457.99337009, 12070.36182056,
        1316.80390171, 12487.96323829,  1510.21578897,  8686.61631648,
        1917.94823503, 33976.051196  , 10897.76685209,  2664.19253141,
       25722.20755627, 26424.13370362,  9479.10796232,  1863.83912819,
       13329.7723369 ,  1073.61302904, 10341.42568066, 10645.06704182,
       16881.69295598, 26921.05117064,  7018.11372945,  5132.17836741,
        5920.68723568, 13286.63963147, 11158.68844933,  8416.8061733 ,
        5167.93837874, 12337.68405646, 13895.15868409, 35836.96175984,
        4196.89009822, 28980.44891414,  -961.26780724,  2921.86613551,
       11099.76872758, 15744.08933868,  5281.13834944,  6966.55421472,
        3803.79903861, 31254.63731888,  7290.78038826, 12478.2106801 ,
        5672.84238242,  9467.08985744, 36371.28884622,  4496.76456866,
        9618.30924417, 31093.76073053,  5792.96431271,  4658.92216117,
        1107.79348298,  4889.10390822,  4520.98494337,  6448.72766906,
       18721.14612088, -1478.93974377,  2319.22491117, 10632.53004384,
        3098.96164698, 10157.35793398,  3769.16137642,  5174.54443788,
       12346.89443635,  6255.19734761,  8183.12855814,  7539.04857852,
        8976.47989633, 10544.75533025, 27883.56216637, 39118.98321979,
       11822.87065627,  7628.83705103, 40956.39772697, 12258.19645795])

In [22]:
r2 = r2_score(pred , Y_test)
print("R2 Score: ",r2)

R2 Score:  0.7086297888685129

In [28]:
result = pd.DataFrame({
    "Actual": Y_test.values,
    "Predicted": pred
})

result.head(10)

     Actual     Predicted
0   9095.07   8931.642854
1   5272.18   7108.658375
2  29330.98  36911.245886
3   9301.89   9492.186731
4  33750.29  27005.514588
5   4536.26  10792.513197
6   2117.34    219.461966
7  14210.54  16940.946999
8   3732.63   1057.144343
9  10264.44  11271.119764